function include(jsFile){
	document.write('<script type="text/javascript" src="'+jsFile+'"></script>');
}


include('../frameworks2/src/dataModels/DataModel.js');

// some data models require to be before -->
include('../frameworks2/src/dataModels/lists/List.js');
include('../frameworks2/src/dataModels/numbers/NumberList.js');
include('../frameworks2/src/dataModels/networks/elements/Node.js');
include('../frameworks2/src/dataModels/networks/lists/NodeList.js');
include('../frameworks2/src/dataModels/networks/lists/RelationList.js');
include('../frameworks2/src/dataModels/lists/Table.js');

include('../frameworks2/src/dataModels/dates/DateAxis.js');
include('../frameworks2/src/dataModels/dates/DateInterval.js');
include('../frameworks2/src/dataModels/dates/DateList.js');
include('../frameworks2/src/dataModels/geo/Country.js');
include('../frameworks2/src/dataModels/geo/CountryList.js');
include('../frameworks2/src/dataModels/geometry/Point.js');
include('../frameworks2/src/dataModels/geometry/Point3D.js');
include('../frameworks2/src/dataModels/geometry/Polygon.js');
include('../frameworks2/src/dataModels/geometry/Polygon3D.js');
include('../frameworks2/src/dataModels/geometry/Polygon3DList.js');
include('../frameworks2/src/dataModels/geometry/PolygonList.js');
include('../frameworks2/src/dataModels/geometry/Rectangle.js');
include('../frameworks2/src/dataModels/geometry/RectangleList.js');
include('../frameworks2/src/dataModels/graphic/ColorList.js');
include('../frameworks2/src/dataModels/graphic/ColorScale.js');
include('../frameworks2/src/dataModels/numbers/Axis.js');
include('../frameworks2/src/dataModels/numbers/Axis2D.js');
include('../frameworks2/src/dataModels/numbers/Interval.js');
include('../frameworks2/src/dataModels/numbers/Matrix.js');
include('../frameworks2/src/dataModels/numbers/NumberTable.js');
include('../frameworks2/src/dataModels/spaces/Space2D.js');
include('../frameworks2/src/dataModels/strings/StringList.js');
include('../frameworks2/src/dataModels/networks/elements/Relation.js');
include('../frameworks2/src/dataModels/networks/networks/Network.js');
include('../frameworks2/src/dataModels/networks/networks/Tree.js');

////operators
include('../frameworks2/src/operators/objects/ObjectOperators.js');
include('../frameworks2/src/operators/objects/ObjectConversions.js');
include('../frameworks2/src/operators/dates/DateListOperators.js');
include('../frameworks2/src/operators/dates/DateOperators.js');
include('../frameworks2/src/operators/geo/CountryListOperators.js');
include('../frameworks2/src/operators/geo/CountryOperators.js');
include('../frameworks2/src/operators/geo/GeoOperators.js');
include('../frameworks2/src/operators/geometry/GeometryConversions.js');
include('../frameworks2/src/operators/geometry/GeometryOperators.js');
include('../frameworks2/src/operators/geometry/PointOperators.js');
include('../frameworks2/src/operators/geometry/PolygonGenerators.js');
include('../frameworks2/src/operators/geometry/PolygonListEncodings.js');
include('../frameworks2/src/operators/geometry/PolygonListOperators.js');
include('../frameworks2/src/operators/geometry/PolygonOperators.js');
include('../frameworks2/src/operators/geometry/RectangleOperators.js');
include('../frameworks2/src/operators/graphic/ColorConvertions.js');
include('../frameworks2/src/operators/graphic/ColorGenerators.js');
include('../frameworks2/src/operators/graphic/ColorListGenerators.js');
include('../frameworks2/src/operators/graphic/ColorListOperators.js');
include('../frameworks2/src/operators/graphic/ColorOperators.js');
include('../frameworks2/src/operators/graphic/ColorScales.js');
include('../frameworks2/src/operators/graphic/ColorScaleGenerators.js');
include('../frameworks2/src/operators/lists/ListGenerators.js');
include('../frameworks2/src/operators/lists/ListOperators.js');
include('../frameworks2/src/operators/lists/TableConversions.js');
include('../frameworks2/src/operators/lists/TableEncodings.js');
include('../frameworks2/src/operators/lists/TableGenerators.js');
include('../frameworks2/src/operators/lists/TableOperators.js');
include('../frameworks2/src/operators/numbers/interval/IntervalListOperators.js');
include('../frameworks2/src/operators/numbers/interval/IntervalTableOperators.js');
include('../frameworks2/src/operators/numbers/MatrixGenerators.js');
include('../frameworks2/src/operators/numbers/numberList/NumberListGenerators.js');
include('../frameworks2/src/operators/numbers/numberList/NumberListOperators.js');
include('../frameworks2/src/operators/numbers/NumberOperators.js');
include('../frameworks2/src/operators/numbers/numberTable/NumberTableConversions.js');
include('../frameworks2/src/operators/numbers/numberTable/NumberTableFlowOperators.js');
include('../frameworks2/src/operators/numbers/numberTable/NumberTableOperators.js');
//include('../frameworks2/src/operators/numbers/UniversalNumericOperators.js');
include('../frameworks2/src/operators/strings/StringConversions.js');
include('../frameworks2/src/operators/strings/StringListOperators.js');
include('../frameworks2/src/operators/strings/StringOperators.js');
include('../frameworks2/src/operators/networks/NetworkConvertions.js');
include('../frameworks2/src/operators/networks/NetworkEncodings.js');
include('../frameworks2/src/operators/networks/NetworkGenerators.js');
include('../frameworks2/src/operators/networks/NetworkOperators.js');
include('../frameworks2/src/operators/networks/TreeConversions.js');
include('../frameworks2/src/operators/networks/TreeEncodings.js');

////apis
//include('../frameworks2/src/apis/delicious/LoadDeliciousTagsFromWebsite.js');
//include('../frameworks2/src/apis/geo/CountriesApi.js');
//include('../frameworks2/src/apis/remarkableWords/RemarkableWordsApi.js');
//include('../frameworks2/src/apis/twitter/networks/MentionRelation.js');
//include('../frameworks2/src/apis/twitter/networks/MergedRelation.js');
//include('../frameworks2/src/apis/twitter/networks/RTRelation.js');
//include('../frameworks2/src/apis/twitter/networks/TweetNode.js');
//include('../frameworks2/src/apis/twitter/networks/TwitterUserNode.js');
//include('../frameworks2/src/apis/twitter/TweetsOperators.js');
//include('../frameworks2/src/apis/twitter/TwitterApi.js');
//include('../frameworks2/src/apis/twitter/TwitterCommunityMetrics.js');
//include('../frameworks2/src/apis/twitter/TwitterSearch.js');
//include('../frameworks2/src/apis/twitter/TwitterSearchProcesses.js');
//include('../frameworks2/src/apis/wikipedia/WikipediaArticlesApi.js');
//include('../frameworks2/src/apis/wikipedia/WikipediaArticlesOperators.js');
//include('../frameworks2/src/apis/wikipedia/WikipediaArticlesVisits.js');

////Tools
include('../frameworks2/src/Tools/graphic/CanvasAndContext.js');
include('../frameworks2/src/Tools/graphic/Draw.js');
include('../frameworks2/src/Tools/graphic/DrawSimpleVis.js');
include('../frameworks2/src/Tools/graphic/DrawTexts.js');
include('../frameworks2/src/Tools/graphic/DrawTextsAdvanced.js');
//include('../frameworks2/src/Tools/graphic/ImageGenerators.js');
include('../frameworks2/src/Tools/graphic/SimpleGraphics.js');
//include('../frameworks2/src/Tools/interaction/ColorPicker.js');
include('../frameworks2/src/Tools/interaction/DragDetection.js');
//include('../frameworks2/src/Tools/interaction/InputTextField.js');
include('../frameworks2/src/Tools/interaction/InputTextFieldHTML.js');
//include('../frameworks2/src/Tools/interaction/Selection.js');
include('../frameworks2/src/Tools/interaction/TextBox.js');
//include('../frameworks2/src/Tools/interaction/TextButton.js');
include('../frameworks2/src/Tools/interaction/TextFieldHTML.js');
//include('../frameworks2/src/Tools/interaction/ToolTip.js');
include('../frameworks2/src/Tools/loaders/Loader.js');
include('../frameworks2/src/Tools/loaders/LoadEvent.js');
include('../frameworks2/src/Tools/loaders/MultiLoader.js');
include('../frameworks2/src/Tools/physics/Forces.js');
include('../frameworks2/src/Tools/threeD/Engine3D.js');
include('../frameworks2/src/Tools/utils/code/ClassUtils.js');
include('../frameworks2/src/Tools/utils/strings/ConsoleTools.js');
include('../frameworks2/src/Tools/utils/strings/FastHtml.js');
include('../frameworks2/src/Tools/utils/strings/JSONUtils.js');
include('../frameworks2/src/Tools/utils/strings/MD5.js');
include('../frameworks2/src/Tools/utils/strings/StringUtils.js');
//include('../frameworks2/src/Tools/utils/strings/SVGdecode.js');
include('../frameworks2/src/Tools/utils/system/Navigator.js');

////visualization
include('../frameworks2/src/visualization/geo/CountryListDraw.js');
include('../frameworks2/src/visualization/geometry/CirclesVisOperators.js');
include('../frameworks2/src/visualization/graphic/ColorsDraw.js');
include('../frameworks2/src/visualization/graphic/ImageDraw.js');
include('../frameworks2/src/visualization/lists/ListDraw.js');
include('../frameworks2/src/visualization/numbers/IntervalTableDraw.js');
include('../frameworks2/src/visualization/numbers/NumberTableDraw.js');
include('../frameworks2/src/visualization/numbers/NumberListDraw.js');
include('../frameworks2/src/visualization/objects/ObjectDraw.js');
include('../frameworks2/src/visualization/strings/StringDraw.js');
include('../frameworks2/src/visualization/strings/StringListDraw.js');
include('../frameworks2/src/visualization/strings/StringListVisOperators.js');
include('../frameworks2/src/visualization/networks/NetworkDraw.js');
include('../frameworks2/src/visualization/networks/TreeDraw.js');

////Global
include('../frameworks2/src/Global.js');
